Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 'ddd'
'ddd'
>>> sac
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    sac
NameError: name 'sac' is not defined
>>> 'ascascascasc'
'ascascascasc'
>>> 'ascascascsc'
'ascascascsc'
>>> 'dasdad'
'dasdad'
>>> 'dadad
SyntaxError: EOL while scanning string literal
>>> 'dadasdad'
'dadasdad'
>>> hppt://tinyurl.com/h4qntgk
>>> for i in range(100) :
	('hello,world!')

	
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
>>> # hppt://tinyurl.com/h4qntgk
>>> for i in(100):
	('hello,world')

	
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    for i in(100):
TypeError: 'int' object is not iterable
>>> # hppt://tinyurl.com/h4qntgk
>>> for i in(100):
	print('hello,world')

	
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    for i in(100):
TypeError: 'int' object is not iterable
>>> 
>>> # hppt://tinyurl.com/h4qntgk
>>> for i in range(100):
	('hello,world!')

	
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
'hello,world!'
>>> 
